name = "Boss Music Swapper"
description = "Swaps music during boss fights"
author = "jimmybaxter"
version = "1.0"
api_version = 10
dst_compatible = true
all_clients_require_mod = false
client_only_mod = true
icon_atlas = "modicon.xml"
icon = "modicon.tex"
server_filter_tags = {}
forumthread = ""
configuration_options = {}
